spring.data.elasticsearch.properties.index.search.slowlog.threshold.query.info: 1ms

logging:
  level:
    root: INFO


spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300